import { chromium } from 'playwright';
import { resolve } from 'node:path';
import { mkdirSync } from 'node:fs';
const url = process.argv[2] || 'http://localhost:4324/lab';
const outDir = resolve('./out-lab');
mkdirSync(outDir, { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1320, height: 1100 }, deviceScaleFactor: 2 });
const errors = [];
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push('console.error: ' + m.text()); });
await page.goto(url, { waitUntil: 'networkidle' });
await page.reload({ waitUntil: 'networkidle' });
await page.waitForTimeout(1100);
const el = await page.$('.sess-detail');
if (el) await el.screenshot({ path: resolve(outDir, 'session.png') });
else errors.push('missing .sess-detail');
await browser.close();
console.log('shot → out-lab/session.png');
console.log('pageerrors:', errors.length ? '\n  - ' + errors.join('\n  - ') : 'none');
