#!/usr/bin/env python3
"""Per-step input and output token-length distributions for the paper's
"Input/Output length distribution" table (``tab:token_length_distribution`` in
``src/05_LLMGeneration.tex``), split by provider (Claude vs Codex).

For each provider we report, over all LLM steps (rounds), the avg / p25 / p50 /
p90 / p99 of three per-step token counts:

* **Prefix tokens** -- ``prefix_tokens`` (the replayed accumulated context).
* **Append tokens** -- ``newly_append_tokens`` (freshly added uncached input).
* **Output tokens** -- ``output_tokens`` (generated tokens, reasoning included).

The prefix/append split mirrors ``llm_generation/prefix_append_distribution`` and
the output column mirrors ``llm_generation/output_tokens``; here we additionally
emit the single combined paper table that the Input- and Output-length-distribution
subsections share. Distributions are exact -- DuckDB keeps every row, so the
percentiles and means run over all valid rounds (no reservoir sampling).

Run with the standard trace-db CLI (``--db`` | ``-i/--input`` | ``-o/--output-dir``).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

EXP_DIR = Path(__file__).resolve().parent
REPO_ROOT = EXP_DIR.parents[2]  # token_length_distribution -> llm_generation -> artifacts -> repo root
sys.path.insert(0, str(REPO_ROOT / "artifacts" / "utils"))

import trace_db  # noqa: E402

PERCENTILES = (25, 50, 90, 99)
# (provider value in the trace, display label) -- the two providers present in the trace.
PROVIDERS = (("claude", "Claude"), ("codex", "Codex"))
# (column, block label) -- order: prefix, append (= input length), then output.
METRICS = (
    ("prefix_tokens", "Prefix tokens"),
    ("newly_append_tokens", "Append tokens"),
    ("output_tokens", "Output tokens"),
)


def _stats(arr: np.ndarray) -> dict[str, float]:
    if not arr.size:
        return {"avg": 0.0, "p25": 0.0, "p50": 0.0, "p90": 0.0, "p99": 0.0, "count": 0}
    row: dict[str, float] = {"avg": float(arr.mean()), "count": int(arr.size)}
    row.update({f"p{q}": float(v) for q, v in zip(PERCENTILES, np.percentile(arr, PERCENTILES))})
    return row


def collect(con) -> dict[str, dict[str, dict[str, float]]]:
    """Return ``stats[provider][column] = {avg,p25,p50,p90,p99,count}`` over all valid rounds.

    Each token column is filtered independently to non-null, non-negative values, matching the
    prefix_append_distribution / output_tokens experiments.
    """
    out: dict[str, dict[str, dict[str, float]]] = {}
    for prov, _ in PROVIDERS:
        out[prov] = {}
        for column, _ in METRICS:
            rows = con.execute(
                f"SELECT CAST({column} AS DOUBLE) FROM rounds "
                f"WHERE provider = ? AND {column} IS NOT NULL AND {column} >= 0",
                [prov],
            ).fetchall()
            out[prov][column] = _stats(np.asarray([r[0] for r in rows], dtype=float))
    return out


def toks(x: float) -> str:
    """Integer token count with thousands separators."""
    return f"{x:,.0f}"


def render_tex(stats: dict[str, dict[str, dict[str, float]]]) -> str:
    def cells(s: dict[str, float]) -> str:
        return " & ".join(toks(s[k]) for k in ("avg", "p25", "p50", "p90", "p99"))

    lines = [
        "% AUTO-GENERATED by artifacts/llm_generation/token_length_distribution/analyze.py -- do",
        "% not edit by hand; re-run on the trace to refresh.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Per-step prefix, append, and output token length distribution.}",
        "\\label{tab:token_length_distribution}",
        "\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\renewcommand{\\arraystretch}{1.15}",
        "\\begin{tabular}{l r r r r r}",
        "\\toprule",
        "\\textbf{Tokens} & \\textbf{Avg} & \\textbf{P25} & \\textbf{P50} & \\textbf{P90} "
        "& \\textbf{P99} \\\\",
        "\\midrule",
    ]
    for mi, (column, mlabel) in enumerate(METRICS):
        if mi:
            lines.append("\\addlinespace")
        lines.append(f"\\multicolumn{{6}}{{@{{}}l}}{{\\emph{{{mlabel}}}}} \\\\")
        for prov, plabel in PROVIDERS:
            lines.append(f"\\quad {plabel} & {cells(stats[prov][column])} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def render_stdout(stats: dict[str, dict[str, dict[str, float]]]) -> str:
    out: list[str] = []
    for prov, plabel in PROVIDERS:
        out.append(f"[{plabel}]")
        for column, mlabel in METRICS:
            s = stats[prov][column]
            out.append(
                f"  {mlabel:28s} n={int(s['count']):>9,}  avg {toks(s['avg']):>10s}  "
                f"p25 {toks(s['p25']):>10s}  p50 {toks(s['p50']):>10s}  "
                f"p90 {toks(s['p90']):>10s}  p99 {toks(s['p99']):>10s}"
            )
        out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    trace_db.add_db_args(parser, default_output_dir=EXP_DIR)
    args = parser.parse_args()

    con = trace_db.open_from_args(args)
    try:
        stats = collect(con)
    finally:
        con.close()

    out_path = Path(args.output_dir) / "token_length_distribution.tex"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_tex(stats), encoding="utf-8")

    print(render_stdout(stats))
    print(f"Wrote {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
